# Generated by Django 2.2.1 on 2019-07-21 01:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('busyapp', '0003_auto_20190721_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 1, 8, 19, 228973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 21, 1, 8, 19, 228440, tzinfo=utc)),
        ),
    ]
