# Generated by Django 2.2.1 on 2019-07-25 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('busyapp', '0004_auto_20190721_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 2, 36, 11, 399058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 25, 2, 36, 11, 398472, tzinfo=utc)),
        ),
    ]
