# Generated by Django 2.2.1 on 2019-08-01 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('busyapp', '0005_auto_20190725_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 22, 29, 27, 564746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 1, 22, 29, 27, 564222, tzinfo=utc)),
        ),
    ]
