# Generated by Django 2.2.1 on 2019-07-18 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('busyapp', '0016_auto_20190718_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_info',
            new_name='userinfo',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 21, 16, 23, 320378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 21, 16, 23, 319581, tzinfo=utc)),
        ),
    ]
