# Generated by Django 2.2.1 on 2019-07-18 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 7, 18, 18, 40, 53, 476755, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
