# Generated by Django 2.2.1 on 2019-07-19 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0027_auto_20190718_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 19, 0, 54, 347990, tzinfo=utc)),
        ),
    ]
