# Generated by Django 2.2.1 on 2019-07-19 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0028_auto_20190719_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 19, 5, 46, 219747, tzinfo=utc)),
        ),
    ]
