# Generated by Django 2.2.1 on 2019-07-19 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0029_auto_20190719_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 19, 6, 8, 993359, tzinfo=utc)),
        ),
    ]
