# Generated by Django 2.2.1 on 2019-07-19 23:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0034_auto_20190719_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 23, 53, 32, 313139, tzinfo=utc)),
        ),
    ]
