# Generated by Django 2.2.1 on 2019-07-19 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0035_auto_20190719_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 23, 59, 29, 692135, tzinfo=utc)),
        ),
    ]
