# Generated by Django 2.2.1 on 2019-07-20 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0036_auto_20190719_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 17, 17, 24, 930049, tzinfo=utc)),
        ),
    ]
