# Generated by Django 2.2.1 on 2019-07-21 00:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_auto_20190720_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 0, 46, 44, 480023, tzinfo=utc)),
        ),
    ]
